### ISSUE TITLE
The setx commands in the instructions don't work

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/clesperantoj_prototype#9] opened 2023-02-07 12:36 UTC
On my Windows, I cannot change the PATH as described in the instructions:

![image](https://user-images.githubusercontent.com/12660498/217246183-0ffdc80c-a801-4fa5-b1ac-2a794f933739.png)

The PATH variable remains unchanged. With `set ...` instead of `setx ...` it works. Is there any reason why our instructions use `setx`?

**Comment by haesleinhuepf** [comment] 2023-02-07 12:37
Also setting JAVA_HOME doesn't work apparently, neither with `set` nor with `setx`:

![image](https://user-images.githubusercontent.com/12660498/217246852-da168a10-421a-4e9c-80e7-871797ab52c4.png)

**Comment by haesleinhuepf** [comment] 2023-02-07 12:42
I found the issue: We must use `SET variable=value` (note the equal sign)

**Comment by StRigaud** [comment] 2023-02-07 13:10
Maybe setting up the path variable using Windows GUI is better for a start.

Tbh, I have not tested the instructions for windows. Maybe better to debug this together 😄

**Comment by haesleinhuepf** [comment] 2023-02-08 12:48
Yes, I just did it like this (for the record):

![image](https://user-images.githubusercontent.com/12660498/217533939-d8e35e38-86a7-4d53-be89-4aad36b15c7a.png)

**Comment by haesleinhuepf** [comment] 2023-02-08 12:50
... and I also had to add this to the PATH:
```
C:\Program Files\CMake\bin
```

**Comment by stefanhahmann** [comment] 2023-03-23 16:14
On my machine, there was no OpenCL available out of the box. I there tried installing CUDA Toolkit. That seems to add OpenCL for Nvidia graphic cards: https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=10

![grafik](https://user-images.githubusercontent.com/10515534/227266455-86110a6f-5d44-4b4d-ba98-0e50cd5e7272.png)

I also added C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\lib\x64 to the Path, since it contains the OpenCL.dll.

![grafik](https://user-images.githubusercontent.com/10515534/227266913-359eb17f-8e47-4ada-8c5e-4ec221daa9a8.png)

**Comment by StRigaud** [comment] 2023-03-23 16:51
On windows with CUDA, we normally need is to have the environment variable CUDA_PATH filled up. CMake will use it and concats the `/lib/x64` to find OpenCL. See [FindOpenCL](https://github.com/Kitware/CMake/blob/c96f97701728c56827092ba562ecb4f44bda0c76/Modules/FindOpenCL.cmake#L102-L142)

However for compilation you will need to have the path up to date here:
https://github.com/clEsperanto/clesperantoj_prototype/blob/cb3d98973c19d352eadf08f62635d5c6bd57cae2/pom.xml#L169-L172

**Comment by stefanhahmann** [comment] 2023-03-24 09:46
> 

Thanks for the hint. Cuda installation added that environment variable for me: 
![grafik](https://user-images.githubusercontent.com/10515534/227483377-58f1123b-0cad-4f51-8047-3a6c304654b2.png)

However, in CMake, I am still getting this, even though OpenCL has actually been installed with Cuda installation.
![grafik](https://user-images.githubusercontent.com/10515534/227483667-0472a599-ca11-4824-b02b-14427f8fed03.png)

During CLic build, I am using "ALL_BUILD" (is that actually correct? there are plenty of different build options), it complains that the file "OpenCL-LIBRARY-NOTFOUND.lib" cannot be opened. The Build eventually fails afterwards.
Apologies for the German error messages. My installation of Visual Studio does not provide English as a language to set.

**Comment by StRigaud** [comment] 2023-03-24 13:34
Okay, and does it find OpenCL if you put back the full path inside the PATH? Not just CUDA_PATH?

**Comment by stefanhahmann** [comment] 2023-03-24 15:11
I hade to manually copy OpenCL.lib to here to get around this:

![grafik](https://user-images.githubusercontent.com/10515534/227564673-44e40802-2bcf-4a0d-a272-848962fd77c8.png)

After that the build worked.

Any ideas what I did wrong that this manual copying step was necessary?

**Comment by StRigaud** [comment] 2023-03-24 17:01
From the error you screened, the issue is at the java wrapper compilation where it reques OpenCL for LINK.

This was solved for me by adding the linkpath to the pom.xml
```xml
<linkPath>C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v{cuda.version}/lib/x64/</linkPath>
```
Alternative, but ugly though is to set the path directly in the `linkPath` of the `properties` in the JAVACPP presets

https://github.com/clEsperanto/clesperantoj_prototype/blob/7cf130d225ecd57e78f4bfa32753b10c6b9e668c/src/main/java/net/clesperanto/presets/clesperantoj.java#L12-L16

This is what Robert did here in a alternative branch

https://github.com/clEsperanto/clesperantoj_prototype/blob/f5284c7c3f0e194ece2b07a696ed6c876642196f/src/main/java/net/clesperanto/clicwrapper/clesperantoj.java#L20-L22

**Comment by stefanhahmann** [comment] 2023-03-27 15:00
> 

The pom.xml way did not work for me. However, adding the linkPath in the JAVACPP presets works for me (in this cases, I do not have to copy manually the OpenCL.lib file to the lib folder).

**Comment by StRigaud** [comment] 2023-03-28 08:26
Okay, this is weird because it is the same thing behind, just two different way to pass the information to the compiler.

Last issue I can see is the use of `\` instead of '/' or a small mistake in the path.

This OpenCL path is an issue ...

**Comment by stefanhahmann** [comment] 2023-03-28 11:17
> Okay, this is weird because it is the same thing behind, just two different way to pass the information to the compiler.
> 
> Last issue I can see is the use of `\` instead of '/' or a small mistake in the path.
> 
> This OpenCL path is an issue ...

I checked again with '\' instead of '/' in the pom.xml, but this did not change anything. Also I double checked again the path. There was no mistake. It is the same path that I pass in clesperantoj.java

**Comment by StRigaud** [comment] 2024-06-18 11:06
Hey @stefanhahmann 

Could you rety again to build the project on your computer? We have updated the pom.xml and the build process, hopefully solving this issue. All tests we did locally worked, would be great to confirm with you :)

Thanks!
Best

**Comment by StRigaud** [comment] 2024-07-31 09:33
Install and build instruction have been updated and build procedure has been upgraded.
I close the issue, do not hesitate to reopen if needed.

**Closed by StRigaud** 2024-07-31 09:33 UTC
